# Generated by Django 4.2.2 on 2023-06-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='size',
        ),
        migrations.AddField(
            model_name='finch',
            name='wing_span',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
